<a href="https://colab.research.google.com/github/AishwaryaVelumani/Siesgstarena-ML/blob/master/Codeforces_API_Content_Based_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
import requests
import json
import pprint
import pandas as pd

# Fetching the data from the API

In [107]:
cf_prob= requests.get('https://codeforces.com/api/problemset.problems?tags=implementation')

In [108]:
print(type(cf_prob))

<class 'requests.models.Response'>


In [109]:
pprint.pprint(cf_prob.json())

Streaming output truncated to the last 5000 lines.
                          'index': 'C',
                          'name': 'Predict Outcome of the Game',
                          'points': 1500.0,
                          'rating': 1700,
                          'tags': ['brute force', 'implementation', 'math'],
                          'type': 'PROGRAMMING'},
                         {'contestId': 451,
                          'index': 'B',
                          'name': 'Sort the Array',
                          'points': 1000.0,
                          'rating': 1300,
                          'tags': ['implementation', 'sortings'],
                          'type': 'PROGRAMMING'},
                         {'contestId': 451,
                          'index': 'A',
                          'name': 'Game With Sticks',
                          'points': 500.0,
                          'rating': 900,
                          'tags': ['implementation'],
                 

# Converting json file to a dataframe

In [110]:
cf_prob_dict= cf_prob.json()

In [111]:
type(cf_prob_dict)

dict

In [112]:
print(cf_prob_dict)

{'status': 'OK', 'result': {'problems': [{'contestId': 1405, 'index': 'B', 'name': 'Array Cancellation', 'type': 'PROGRAMMING', 'points': 1000.0, 'rating': 1000, 'tags': ['constructive algorithms', 'implementation']}, {'contestId': 1404, 'index': 'A', 'name': 'Balanced Bitstring', 'type': 'PROGRAMMING', 'points': 500.0, 'rating': 1500, 'tags': ['implementation', 'strings']}, {'contestId': 1396, 'index': 'C', 'name': 'Monster Invaders', 'type': 'PROGRAMMING', 'points': 1750.0, 'rating': 2300, 'tags': ['dp', 'greedy', 'implementation']}, {'contestId': 1403, 'index': 'C', 'name': 'Chess Rush', 'type': 'PROGRAMMING', 'rating': 3200, 'tags': ['*special', 'combinatorics', 'dp', 'implementation', 'math']}, {'contestId': 1402, 'index': 'A', 'name': 'Fancy Fence', 'type': 'PROGRAMMING', 'rating': 1800, 'tags': ['*special', 'data structures', 'dsu', 'implementation', 'math', 'sortings']}, {'contestId': 1401, 'index': 'E', 'name': 'Divide Square', 'type': 'PROGRAMMING', 'points': 2500.0, 'rating'

In [113]:
def flatten_dict(dd, separator ='_', prefix =''): 
    return { prefix + separator + k if prefix else k : v 
             for kk, vv in dd.items() 
             for k, v in flatten_dict(vv, separator, kk).items() 
             } if isinstance(dd, dict) else { prefix : dd }

In [114]:
flat_cf_prob_dict= flatten_dict(cf_prob_dict)

In [115]:
cf_prob_df= pd.DataFrame.from_dict(flat_cf_prob_dict)

In [116]:
cf_prob_df.head()

status  ...                           result_problemStatistics
0     OK  ...  {'contestId': 1405, 'index': 'B', 'solvedCount...
1     OK  ...  {'contestId': 1404, 'index': 'A', 'solvedCount...
2     OK  ...  {'contestId': 1396, 'index': 'C', 'solvedCount...
3     OK  ...  {'contestId': 1403, 'index': 'C', 'solvedCount...
4     OK  ...  {'contestId': 1402, 'index': 'A', 'solvedCount...

[5 rows x 3 columns]

In [117]:
result_prob= cf_prob_df['result_problems']
print(result_prob)

0       {'contestId': 1405, 'index': 'B', 'name': 'Arr...
1       {'contestId': 1404, 'index': 'A', 'name': 'Bal...
2       {'contestId': 1396, 'index': 'C', 'name': 'Mon...
3       {'contestId': 1403, 'index': 'C', 'name': 'Che...
4       {'contestId': 1402, 'index': 'A', 'name': 'Fan...
                              ...                        
1863    {'contestId': 5, 'index': 'A', 'name': 'Chat S...
1864    {'contestId': 4, 'index': 'C', 'name': 'Regist...
1865    {'contestId': 3, 'index': 'C', 'name': 'Tic-ta...
1866    {'contestId': 2, 'index': 'A', 'name': 'Winner...
1867    {'contestId': 1, 'index': 'B', 'name': 'Spread...
Name: result_problems, Length: 1868, dtype: object


In [118]:
print(type(result_prob[1]))

<class 'dict'>


In [119]:
split_result_prob= pd.DataFrame(result_prob.values.tolist(),index=result_prob.index)
print(split_result_prob)

      contestId  ...                                               tags
0          1405  ...          [constructive algorithms, implementation]
1          1404  ...                          [implementation, strings]
2          1396  ...                       [dp, greedy, implementation]
3          1403  ...  [*special, combinatorics, dp, implementation, ...
4          1402  ...  [*special, data structures, dsu, implementatio...
...         ...  ...                                                ...
1863          5  ...                                   [implementation]
1864          4  ...         [data structures, hashing, implementation]
1865          3  ...               [brute force, games, implementation]
1866          2  ...                          [hashing, implementation]
1867          1  ...                             [implementation, math]

[1868 rows x 7 columns]


In [120]:
split_result_prob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1868 entries, 0 to 1867
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   contestId  1868 non-null   int64  
 1   index      1868 non-null   object 
 2   name       1868 non-null   object 
 3   type       1868 non-null   object 
 4   points     1426 non-null   float64
 5   rating     1849 non-null   float64
 6   tags       1868 non-null   object 
dtypes: float64(2), int64(1), object(4)
memory usage: 102.3+ KB


In [121]:
cf_prob_df.drop(['result_problems'],axis=1,inplace=True)
cf_prob_df.head()

status                           result_problemStatistics
0     OK  {'contestId': 1405, 'index': 'B', 'solvedCount...
1     OK  {'contestId': 1404, 'index': 'A', 'solvedCount...
2     OK  {'contestId': 1396, 'index': 'C', 'solvedCount...
3     OK  {'contestId': 1403, 'index': 'C', 'solvedCount...
4     OK  {'contestId': 1402, 'index': 'A', 'solvedCount...

In [122]:
cf_prob_df= pd.concat([cf_prob_df,split_result_prob],axis=1)
cf_prob_df.head()

status  ...                                               tags
0     OK  ...          [constructive algorithms, implementation]
1     OK  ...                          [implementation, strings]
2     OK  ...                       [dp, greedy, implementation]
3     OK  ...  [*special, combinatorics, dp, implementation, ...
4     OK  ...  [*special, data structures, dsu, implementatio...

[5 rows x 9 columns]

In [123]:
cf_prob_df.drop(['result_problemStatistics'],axis=1,inplace=True)
cf_prob_df.head()

status  contestId  ...  rating                                               tags
0     OK       1405  ...  1000.0          [constructive algorithms, implementation]
1     OK       1404  ...  1500.0                          [implementation, strings]
2     OK       1396  ...  2300.0                       [dp, greedy, implementation]
3     OK       1403  ...  3200.0  [*special, combinatorics, dp, implementation, ...
4     OK       1402  ...  1800.0  [*special, data structures, dsu, implementatio...

[5 rows x 8 columns]

In [124]:
cf_prob_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1868 entries, 0 to 1867
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   status     1868 non-null   object 
 1   contestId  1868 non-null   int64  
 2   index      1868 non-null   object 
 3   name       1868 non-null   object 
 4   type       1868 non-null   object 
 5   points     1426 non-null   float64
 6   rating     1849 non-null   float64
 7   tags       1868 non-null   object 
dtypes: float64(2), int64(1), object(5)
memory usage: 116.9+ KB


In [125]:
a= 5.0
b=str(a)
print(type(b))

<class 'str'>


In [126]:
cf_prob_df['rating']= cf_prob_df['rating'].astype(str)
cf_prob_df['points']=cf_prob_df['points'].astype(str)

In [127]:
cf_prob_df.head()

status  contestId  ...  rating                                               tags
0     OK       1405  ...  1000.0          [constructive algorithms, implementation]
1     OK       1404  ...  1500.0                          [implementation, strings]
2     OK       1396  ...  2300.0                       [dp, greedy, implementation]
3     OK       1403  ...  3200.0  [*special, combinatorics, dp, implementation, ...
4     OK       1402  ...  1800.0  [*special, data structures, dsu, implementatio...

[5 rows x 8 columns]

In [128]:
cf_prob_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1868 entries, 0 to 1867
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   status     1868 non-null   object
 1   contestId  1868 non-null   int64 
 2   index      1868 non-null   object
 3   name       1868 non-null   object
 4   type       1868 non-null   object
 5   points     1868 non-null   object
 6   rating     1868 non-null   object
 7   tags       1868 non-null   object
dtypes: int64(1), object(7)
memory usage: 116.9+ KB


In [129]:
def ListToString(s):
    str_rating= ""

    for ele in s:
        str_rating = str_rating+" "+ele
     
    return str_rating


In [130]:
print(ListToString(['abc','def','ghi']))

 abc def ghi


In [131]:
#cf_prob_df['string_tags']= ListToString(cf_prob_df['tags'])

In [132]:
for ind in cf_prob_df.index:
    #print(cf_prob_df['tags'][ind])
    tag=(ListToString(cf_prob_df['tags'][ind]))
    #print(tag)
    cf_prob_df['tags'][ind]=tag
    
cf_prob_df['tags']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """


0                  constructive algorithms implementation
1                                  implementation strings
2                                dp greedy implementation
3           *special combinatorics dp implementation math
4        *special data structures dsu implementation m...
                              ...                        
1863                                       implementation
1864               data structures hashing implementation
1865                     brute force games implementation
1866                               hashing implementation
1867                                  implementation math
Name: tags, Length: 1868, dtype: object

In [152]:
cf_prob_df['SerialNo']=cf_prob_df.index
cf_prob_df.head()

status  ...  SerialNo
0     OK  ...         0
1     OK  ...         1
2     OK  ...         2
3     OK  ...         3
4     OK  ...         4

[5 rows x 10 columns]

In [134]:
#cf_prob_df.drop(columns=['tags'],inplace=True)
#cf_prob_df.head()

# Content Based Recommender System

In [140]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [141]:
features= ['type','points','tags','rating']

In [142]:
def combine_features(row):
    return row['type']+' '+row['points']+' '+ row['tags']+' '+row['rating']

In [143]:
for feature in features:
    cf_prob_df[feature]= cf_prob_df[feature].fillna('')

cf_prob_df['combined_features']= cf_prob_df.apply(combine_features,axis=1)

In [144]:
print(cf_prob_df['combined_features'][0])

PROGRAMMING 1000.0  constructive algorithms implementation 1000.0


In [145]:
cv= CountVectorizer()
count_matrix= cv.fit_transform(cf_prob_df['combined_features'])

In [146]:
print(count_matrix)

  (0, 78)	1
  (0, 0)	2
  (0, 48)	1
  (0, 40)	1
  (0, 64)	1
  (1, 78)	1
  (1, 64)	1
  (1, 35)	1
  (1, 88)	1
  (1, 6)	1
  (2, 78)	1
  (2, 64)	1
  (2, 9)	1
  (2, 52)	1
  (2, 62)	1
  (2, 16)	1
  (3, 78)	1
  (3, 64)	1
  (3, 52)	1
  (3, 72)	1
  (3, 86)	1
  (3, 46)	1
  (3, 68)	1
  (3, 28)	1
  (4, 78)	1
  :	:
  (1863, 72)	1
  (1864, 78)	1
  (1864, 64)	1
  (1864, 72)	1
  (1864, 49)	1
  (1864, 89)	1
  (1864, 63)	1
  (1864, 4)	1
  (1865, 78)	1
  (1865, 64)	1
  (1865, 72)	1
  (1865, 10)	1
  (1865, 44)	1
  (1865, 57)	1
  (1865, 58)	1
  (1866, 78)	1
  (1866, 64)	1
  (1866, 6)	1
  (1866, 72)	1
  (1866, 63)	1
  (1867, 78)	1
  (1867, 64)	1
  (1867, 72)	1
  (1867, 68)	1
  (1867, 7)	1


In [147]:
cos_sim= cosine_similarity(count_matrix)
print(cos_sim)

[[1.         0.31622777 0.28867513 ... 0.26726124 0.31622777 0.31622777]
 [0.31622777 1.         0.36514837 ... 0.3380617  0.6        0.4       ]
 [0.28867513 0.36514837 1.         ... 0.3086067  0.36514837 0.36514837]
 ...
 [0.26726124 0.3380617  0.3086067  ... 1.         0.50709255 0.50709255]
 [0.31622777 0.6        0.36514837 ... 0.50709255 1.         0.6       ]
 [0.31622777 0.4        0.36514837 ... 0.50709255 0.6        1.        ]]


In [153]:
def get_name_from_serialno(serial):
    return cf_prob_df[cf_prob_df.SerialNo==serial]['name'].values[0]

def get_serialno_from_name(name):
    return cf_prob_df[cf_prob_df.name==name]['SerialNo'].values[0]

In [156]:
prob_user_likes= 'Monster Invaders'
prob_serialno= get_serialno_from_name(prob_user_likes)
#print(prob_serialno)
similar_probs= list(enumerate(cos_sim[prob_serialno]))

In [157]:
sorted_similar_probs= sorted(similar_probs,key= lambda x:x[1], reverse=True)[1:]

In [158]:
i=0
print("Top 10 similar problems to "+prob_user_likes+" are:\n")
for element in sorted_similar_probs:
    print(get_name_from_serialno(element[0]))
    i=i+1
    if i>10:
        break

Top 10 similar problems to Monster Invaders are:

Slime
Maximum path
Domino Carpet
Monsters and Potions
Portals
Alice and the Doll
Just Eat It!
Lose it!
Vasya and Templates
Tanks
Odd sum
